/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-dim": "#d7383b",
        "surface-container-lowest": "#000000",
        "on-tertiary": "#440031",
        "error": "#ff716c",
        "on-primary": "#005d63",
        "inverse-primary": "#006a71",
        "surface-bright": "#282c36",
        "surface-variant": "#22262f",
        "primary-dim": "#00deec",
        "primary": "#8ff5ff",
        "on-surface-variant": "#a9abb3",
        "on-primary-fixed": "#003f43",
        "tertiary-dim": "#ff61c8",
        "on-error-container": "#ffa8a3",
        "on-secondary": "#32005c",
        "secondary-dim": "#9c42f4",
        "surface-tint": "#8ff5ff",
        "tertiary-fixed": "#ff89cf",
        "on-surface": "#ecedf6",
        "secondary-container": "#7701d0",
        "background": "#0b0e14",
        "on-secondary-container": "#f0dcff",
        "secondary-fixed": "#e4c6ff",
        "inverse-on-surface": "#52555c",
        "on-secondary-fixed-variant": "#7500cc",
        "outline": "#73757d",
        "tertiary": "#ff61c8",
        "surface-container-high": "#1c2028",
        "on-background": "#ecedf6",
        "on-error": "#490006",
        "on-tertiary-fixed": "#350026",
        "inverse-surface": "#f9f9ff",
        "outline-variant": "#45484f",
        "primary-container": "#00eefc",
        "surface-container-low": "#10131a",
        "tertiary-container": "#fe00c0",
        "on-secondary-fixed": "#4e008a",
        "secondary": "#bf81ff",
        "surface-dim": "#0b0e14",
        "error-container": "#9f0519",
        "primary-fixed": "#00eefc",
        "on-primary-container": "#005359",
        "surface": "#0b0e14",
        "on-tertiary-container": "#000000",
        "on-tertiary-fixed-variant": "#710053",
        "surface-container": "#161a21",
        "primary-fixed-dim": "#00deec",
        "tertiary-fixed-dim": "#ff6eca",
        "on-primary-fixed-variant": "#005e64",
        "surface-container-highest": "#22262f",
        "secondary-fixed-dim": "#dab4ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
